version: '2.0'

services: 

  api:
    container_name: nest_api
    build: .
    ports: 
      - ${API_PORT}:${API_PORT}
    volumes: 
      - .:/home/api
      - /home/api/node_modules
    environment: 
      DB_HOST: db
      DB_PORT: 5432

  db:
    container_name: nest_db
    image: postgres:13
    environment: 
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: 
     - ${DB_PORT}:5432
 